import type { Metadata } from 'next'

const baseUrl = 'https://www.the8thelement.in'

export const seoKeywords = {
  core: [
    'perimenopause',
    'perimenopause symptoms',
    'early perimenopause',
    'signs of perimenopause',
    'am I in perimenopause',
    'menopause',
    'menopause symptoms',
    'postmenopause',
    'hormonal changes',
    'hormone health',
    'healthy menopause',
    'natural menopause support',
    'menopause lifestyle',
    'menopause nutrition',
    'menopause coach',
    'menopause nutrition coach',
    'online menopause coach',
    'menopause consultation',
    'The 8th Element',
    'Srividya Gowri',
    'STRONG-HER',
    'MenoThrive',
    'Transform and Thrive',
  ],
  weightBody: [
    'weight gain after 40',
    'weight gain after menopause',
    'weight gain during perimenopause',
    'menopause belly',
    'perimenopause belly',
    'belly fat',
    'midsection fat',
    'stubborn belly fat',
    'waistline getting bigger',
    'body composition changes',
    'body changes after 40',
    "clothes don't fit anymore",
    "can't lose weight",
    'slow metabolism',
    'fat redistribution',
    'healthy weight loss',
    'sustainable weight loss',
  ],
  strengthAging: [
    'strength training after 40',
    'strength training after menopause',
    'strength training for women',
    'resistance training',
    'weight training for women',
    'build muscle after 40',
    'build muscle after menopause',
    'muscle loss',
    'functional strength',
    'bone health',
    'bone density',
    'osteoporosis prevention',
    'healthy aging',
    'healthy ageing',
    'longevity',
    'healthspan',
    'age stronger',
    'mobility',
    'balance',
  ],
  nutritionLifestyle: [
    'healthy eating',
    'balanced nutrition',
    'meal planning',
    'protein for women',
    'protein after 40',
    'protein after menopause',
    'fiber intake',
    'Indian menopause diet',
    'nutrition for menopause',
    'nutrition after 40',
    'nutrition coaching',
    "women's nutrition",
    'lifestyle nutrition',
    'healthy routines',
    'healthy habits',
    'lifestyle medicine',
    'habit coaching',
    'behaviour change',
    'consistency',
  ],
  symptoms: [
    'poor sleep',
    'insomnia',
    'wake up at 3 am',
    'night waking',
    'night sweats',
    'fatigue',
    'low energy',
    'brain fog',
    'poor focus',
    'mood swings',
    'irritability',
    'anxiety',
    'low mood',
    'stress',
    'burnout',
    'bloating',
    'gut health',
    'digestive issues',
    'low libido',
    'vaginal dryness',
    'joint pain',
  ],
  metabolicHealth: [
    'high cholesterol',
    'high blood pressure',
    'prediabetes',
    'diabetes prevention',
    'insulin resistance',
    'blood sugar',
    'sugar cravings',
    'metabolic health',
    'heart health',
    'inflammation',
    'fatty liver',
    'fatty liver in women',
    'cholesterol after menopause',
    'blood sugar after menopause',
    'metabolic syndrome in women',
  ],
  emotionalEating: [
    'emotional eating',
    'stress eating',
    'comfort eating',
    'mindless eating',
    'late-night snacking',
    'food guilt',
    'all-or-nothing mindset',
    'yo-yo dieting',
    'healthy relationship with food',
  ],
  conditions: [
    'PCOS weight loss',
    'PCOS after 35',
    'Hashimoto weight gain',
    'hypothyroidism weight gain',
    'fibromyalgia fatigue',
    'chronic fatigue in women',
    'sciatica and weight loss',
    'knee pain weight loss',
    'joint pain after 40',
    'midlife inflammation',
  ],
  localIntent: [
    'menopause coach India',
    'menopause nutrition coach India',
    'perimenopause coach India',
    'women health coach India',
    'women weight loss coach India',
    'online nutrition coach India',
    'online menopause consultation India',
    'menopause coach Chennai',
    'nutritionist for menopause Chennai',
    'women wellness coach Chennai',
  ],
  programs: [
    'MenoThrive program',
    'MenoThrive coaching',
    'Transform and Thrive program',
    '1:1 menopause coaching',
    'small group health coaching',
    'menopause health assessment',
    'menopause strategy session',
    'menopause clarity call',
    'perimenopause quiz',
    'menopause stage quiz',
  ],
  outcomes: [
    'lose belly fat',
    'lose weight naturally',
    'build strength',
    'build muscle',
    'feel stronger',
    'feel energetic',
    'sleep better',
    'wake up refreshed',
    'improve confidence',
    'improve body composition',
    'feel like myself again',
    'age well',
    'age with confidence',
    'reduce stress',
    'better habits',
    'long-term health',
  ],
  aiQuestions: [
    'why am I gaining weight after 40',
    "why can't I lose belly fat",
    "why doesn't my old diet work anymore",
    'why am I always tired',
    "why can't I sleep",
    'why do I wake up at 3 am',
    'why do I have brain fog',
    'why am I bloated all the time',
    "why don't I feel like myself anymore",
    'how do I lose weight during menopause',
    'how do I lose belly fat after menopause',
    'how much protein do women need after 40',
    'should women lift weights after 40',
    'is walking enough after menopause',
    'how do I build muscle after 40',
    'how do I age well',
  ],
}

const defaultKeywords = [
  ...seoKeywords.core,
  ...seoKeywords.weightBody.slice(0, 8),
  ...seoKeywords.strengthAging.slice(0, 8),
  ...seoKeywords.nutritionLifestyle.slice(0, 8),
  ...seoKeywords.symptoms.slice(0, 8),
  ...seoKeywords.metabolicHealth.slice(0, 8),
  ...seoKeywords.emotionalEating.slice(0, 8),
  ...seoKeywords.conditions.slice(0, 8),
  ...seoKeywords.localIntent,
  ...seoKeywords.programs,
  ...seoKeywords.outcomes.slice(0, 6),
  ...seoKeywords.aiQuestions.slice(0, 8),
]

export const defaultMetadata: Metadata = {
  metadataBase: new URL(baseUrl),
  title: {
    default: 'Srividya | Menopause Nutrition Lifestyle Weight loss Coach',
    template: '%s | The 8th Element',
  },
  description:
    'Science-backed menopause coaching by Srividya. Personalised nutrition, lifestyle & weight loss coaching to help women reclaim their energy, lose weight, and feel like themselves again.',
  keywords: defaultKeywords,
  authors: [{ name: 'Srividya' }],
  icons: {
    icon: [{ url: '/favicon.svg', type: 'image/svg+xml' }],
    shortcut: ['/favicon.svg'],
  },
  openGraph: {
    type: 'website',
    locale: 'en_IN',
    siteName: 'The 8th Element',
    images: [{ url: '/og-default.jpg', width: 1200, height: 630 }],
  },
  twitter: {
    card: 'summary_large_image',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true },
  },
}

export function buildMeta(overrides: Partial<Metadata>): Metadata {
  return {
    ...defaultMetadata,
    ...overrides,
    keywords: mergeKeywords(defaultMetadata.keywords, overrides.keywords),
  }
}

function mergeKeywords(baseKeywords: Metadata['keywords'], overrideKeywords: Metadata['keywords']) {
  return [...new Set([...normalizeKeywords(baseKeywords), ...normalizeKeywords(overrideKeywords)])]
}

function normalizeKeywords(keywords: Metadata['keywords']) {
  if (!keywords) return []
  return Array.isArray(keywords) ? keywords : [keywords]
}
