export const localBusinessSchema = {
  '@context': 'https://schema.org',
  '@type': 'LocalBusiness',
  name: 'The 8th Element',
  description:
    'Science-backed perimenopause and menopause coaching for women 40+ in Chennai, India.',
  url: 'https://www.the8thelement.in',
  logo: 'https://www.the8thelement.in/logo.svg',
  image: 'https://www.the8thelement.in/logo.svg',
  telephone: '+919884835729',
  email: 'admin@the8thelement.in',
  address: {
    '@type': 'PostalAddress',
    addressLocality: 'Chennai',
    addressRegion: 'Tamil Nadu',
    addressCountry: 'IN',
  },
  openingHoursSpecification: [
    {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '08:00',
      closes: '20:00',
    },
    {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Saturday'],
      opens: '09:00',
      closes: '19:00',
    },
    {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Sunday'],
      opens: '09:00',
      closes: '21:00',
    },
  ],
  sameAs: [
    'https://www.instagram.com/the_8thelement',
    'https://www.youtube.com/@the8thelement',
  ],
  keywords: [
    'perimenopause',
    'menopause symptoms',
    'menopause nutrition',
    'weight gain after 40',
    'strength training after menopause',
    'healthy aging',
    'metabolic health',
    'women health coaching',
  ],
}

export const personSchema = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  name: 'Srividya',
  jobTitle: 'Menopause Nutrition Lifestyle Weight loss Coach',
  image: 'https://www.the8thelement.in/images/srividya.jpg',
  description:
    'Menopause Nutrition, Lifestyle & Weight Loss Coach and founder of The 8th Element.',
  worksFor: {
    '@type': 'Organization',
    name: 'The 8th Element',
  },
  knowsAbout: [
    'Menopause',
    'Perimenopause',
    'Early perimenopause',
    'Perimenopause symptoms',
    'Hormonal changes',
    'Hormone health',
    'Nutrition Coaching',
    'Menopause nutrition',
    "Women's nutrition",
    'Protein after 40',
    'Lifestyle Medicine',
    'Sustainable weight loss',
    'Weight gain after 40',
    'Menopause belly',
    'Body composition changes',
    'Strength training for women',
    'Strength training after menopause',
    'Build muscle after 40',
    'Bone health',
    'Healthy aging',
    'Healthy ageing',
    'Sleep problems',
    'Brain fog',
    'Mood swings',
    'Emotional eating',
    'Stress eating',
    'Gut health',
    'Insulin resistance',
    'Metabolic health',
    'Heart health',
    'Fatty liver',
    'Habit coaching',
    'Behaviour change',
    'Healthy relationship with food',
    'Precision Nutrition',
  ],
}
